# Generated by Django 4.2.14 on 2024-08-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_explorer_api', '0003_dish_food_log_restaurant_foodlogcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_address', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
