# Generated by Django 4.2.14 on 2024-08-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_explorer_api', '0004_restaurants_delete_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='food_image_url',
            field=models.URLField(default='https://example.com/default-image.jpg'),
        ),
    ]
