# Generated by Django 4.2.14 on 2024-08-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_explorer_api', '0005_dish_food_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_log',
            name='food_image',
        ),
        migrations.RemoveField(
            model_name='food_log',
            name='price',
        ),
    ]
