# Generated by Django 4.2.14 on 2024-08-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_explorer_api', '0006_remove_food_log_food_image_remove_food_log_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_log',
            name='category',
        ),
        migrations.AddField(
            model_name='food_log',
            name='category',
            field=models.ManyToManyField(to='culinary_explorer_api.categories'),
        ),
    ]
