# Generated by Django 4.2.14 on 2024-08-17 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_explorer_api', '0007_remove_food_log_category_food_log_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_log',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culinary_explorer_api.dish'),
        ),
        migrations.AlterField(
            model_name='food_log',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culinary_explorer_api.restaurants'),
        ),
        migrations.AlterField(
            model_name='food_log',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culinary_explorer_api.user'),
        ),
    ]
