# Generated by Django 4.2.14 on 2024-08-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_explorer_api', '0009_alter_food_log_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_log',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='food_log',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
