# Generated by Django 4.2.16 on 2025-01-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_explorer_api', '0011_alter_dish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='food_image_url',
            field=models.URLField(default='https://example.com/default-image.jpg', max_length=500),
        ),
    ]
