# Generated by Django 4.2.13 on 2025-02-26 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('culinary_explorer_api', '0013_restaurants_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
