# Generated by Django 4.2.16 on 2025-02-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_explorer_api', '0016_alter_restaurants_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='uid',
            field=models.CharField(default='default_user', max_length=50),
        ),
    ]
