# Generated by Django 4.2.13 on 2024-06-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_alter_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgamer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='eventgamer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventgamer',
            name='game',
        ),
        migrations.RemoveField(
            model_name='eventgamer',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='eventgamer',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='eventgamer',
            name='time',
        ),
        migrations.AddField(
            model_name='eventgamer',
            name='gamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gamer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
